In [ ]:
# calling the pandas library
import pandas as pd
# reading the dataset
diamonds = pd.read_csv(r'C:\Users\orbar\Desktop\Study_materials_HIT\DataScience_HIT_2026\Practice_and_understanding_the_study\diamonds.csv', sep=',', index_col=0)
# displaying the first 5 rows of the dataset
diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
# start 10 rows of the dataset
diamonds.head(10)

    carat        cut color clarity  depth  table  price     x     y     z
1    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [ ]:
# end 10 rows of the dataset
diamonds.tail(10)

       carat        cut color clarity  depth  table  price     x     y     z
53931   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53932   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53933   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53934   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53935   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [ ]:
# Get the shape of the dataset
diamonds.shape

(53940, 10)

In [ ]:
# Get the column names of the dataset
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

In [ ]:
# Get the data types of each column in the dataset
diamonds.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB

In [ ]:
# Get the summary statistics of the dataset
# std - standard deviation
# min - minimum value
# 25% - first quartile
# 50% - median
# 75% - third quartile
# max - maximum value
# it does not shoe the information of type string columns, only numerical columns
diamonds.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [ ]:
# Get the summary statistics of the dataset rounded to 3 decimal places
diamonds.describe().round(3)

,carat,depth,table,price,x,y,z
count,53940.000,53940.000,53940.000,53940.00,53940.000,53940.000,53940.000
mean,0.798,61.749,57.457,3932.80,5.731,5.735,3.539
std,0.474,1.433,2.234,3989.44,1.122,1.142,0.706
min,0.200,43.000,43.000,326.00,0.000,0.000,0.000
25%,0.400,61.000,56.000,950.00,4.710,4.720,2.910
50%,0.700,61.800,57.000,2401.00,5.700,5.710,3.530
75%,1.040,62.500,59.000,5324.25,6.540,6.540,4.040
max,5.010,79.000,95.000,18823.00,10.740,58.900,31.800

In [ ]:
# Get the summary statistics of the dataset including string columns
diamonds.describe(include=["str"])

          cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

In [ ]:
# Get the summary statistics of the dataset including all columns
diamonds.describe(include='all').round(3)

,carat,cut,color,clarity,depth,table,price,x,y,z
count,53940.000,53940,53940,53940,53940.000,53940.000,53940.00,53940.000,53940.000,53940.000
unique,NaN,5,7,8,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Ideal,G,SI1,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,21551,11292,13065,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.798,NaN,NaN,NaN,61.749,57.457,3932.80,5.731,5.735,3.539
std,0.474,NaN,NaN,NaN,1.433,2.234,3989.44,1.122,1.142,0.706
min,0.200,NaN,NaN,NaN,43.000,43.000,326.00,0.000,0.000,0.000
25%,0.400,NaN,NaN,NaN,61.000,56.000,950.00,4.710,4.720,2.910
50%,0.700,NaN,NaN,NaN,61.800,57.000,2401.00,5.700,5.710,3.530
75%,1.040,NaN,NaN,NaN,62.500,59.000,5324.25,6.540,6.540,4.040
max,5.010,NaN,NaN,NaN,79.000,95.000,18823.00,10.740,58.900,31.800

In [ ]:
# Get the unique values of the "cut" column in the dataset
diamonds["cut"].unique()

<StringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

In [ ]:
# Get the unique values of the "Price" column in the dataset
diamonds["price"].head()

1    326
2    326
3    327
4    334
5    335
Name: price, dtype: int64

In [ ]:
# Get the unique values of the "color" & "price" column in the dataset
diamonds[["color", "price"]].head()

  color  price
1     E    326
2     E    326
3     E    327
4     I    334
5     J    335

In [ ]:
# Get the value of the "price" column in the 4th row of the dataset
diamonds.loc[4,"price"]

np.int64(334)

In [ ]:
# Get the values of the "price" column in the 4th to 8th rows of the dataset
diamonds.loc[4:8]

   carat        cut color clarity  depth  table  price     x     y     z
4   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53

In [ ]:
# Get the values of the "depth" and "price" columns in the rows where the "depth" is less than 60
diamonds.loc[diamonds["depth"]<60, ["depth", "price"]]

       depth  price
2       59.8    326
3       56.9    327
10      59.4    338
24      59.4    353
25      58.1    353
...      ...    ...
53903   59.9   2753
53912   59.8   2753
53919   59.3   2753
53928   58.1   2756
53932   59.8   2756

[5114 rows x 2 columns]

In [ ]:
# Get the top 10 rows of the dataset sorted by the "carat" column in descending order
# ascending=False means that the values will be sorted in descending order
diamonds.sort_values(by="carat", ascending=False).head(10)

       carat        cut color clarity  depth  table  price      x      y     z
27416   5.01       Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27631   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27131   4.13       Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
26000   4.01    Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25999   4.01    Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
26445   4.00  Very Good     I      I1   63.3   58.0  15984  10.01   9.94  6.31
26535   3.67    Premium     I      I1   62.4   56.0  16193   9.86   9.81  6.13
23645   3.65       Fair     H      I1   67.1   53.0  11668   9.53   9.48  6.38
27680   3.51    Premium     J     VS2   62.5   59.0  18701   9.66   9.63  6.03
24329   3.50      Ideal     H      I1   62.8   57.0  12587   9.65   9.59  6.03

In [ ]:
# Get the top 10 rows of the dataset sorted by the "carat" column in descending order and save the changes to the original dataset
diamonds.sort_values(by="carat", ascending=False, inplace=True)
diamonds.head(10)

       carat        cut color clarity  depth  table  price      x      y     z
27416   5.01       Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27631   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27131   4.13       Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
26000   4.01    Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25999   4.01    Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
26445   4.00  Very Good     I      I1   63.3   58.0  15984  10.01   9.94  6.31
26535   3.67    Premium     I      I1   62.4   56.0  16193   9.86   9.81  6.13
23645   3.65       Fair     H      I1   67.1   53.0  11668   9.53   9.48  6.38
27680   3.51    Premium     J     VS2   62.5   59.0  18701   9.66   9.63  6.03
24329   3.50      Ideal     H      I1   62.8   57.0  12587   9.65   9.59  6.03

In [ ]:
# Create a new column "price_per_carat" that is the price divided by the carat
diamonds["price_per_carat"] = diamonds["price"] / diamonds["carat"]
# Create a new column "is_expensive" that is True if the price is greater than 10000, False otherwise
diamonds["is_expensive"] = diamonds["price"] > 10000
diamonds.head(10)

,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive
27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,3596.407186,True
27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,4118.000000,True
27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,4195.883777,True
26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,3796.259352,True
25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,3796.259352,True
26445,4.00,Very Good,I,I1,63.3,58.0,15984,10.01,9.94,6.31,3996.000000,True
26535,3.67,Premium,I,I1,62.4,56.0,16193,9.86,9.81,6.13,4412.261580,True
23645,3.65,Fair,H,I1,67.1,53.0,11668,9.53,9.48,6.38,3196.712329,True
27680,3.51,Premium,J,VS2,62.5,59.0,18701,9.66,9.63,6.03,5327.920228,True
24329,3.50,Ideal,H,I1,62.8,57.0,12587,9.65,9.59,6.03,3596.285714,True

In [ ]:
# Create a new column "rate" that is "expensive" if the price is greater than 10000, "cheap" otherwise
import numpy as np
diamonds["rate"] = np.where(diamonds["price"] > 10000, "expensive", "cheap")
diamonds.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive,rate
27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,3596.407186,True,expensive
27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,4118.000000,True,expensive
27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,4195.883777,True,expensive
26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,3796.259352,True,expensive
25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,3796.259352,True,expensive

In [ ]:
# Get the mean of the "price" column in the dataset
diamonds["price"].mean()

np.float64(3932.799721913237)

In [ ]:
# Get the mean of the "price" column in the dataset grouped by the "cut" column
diamonds.groupby("cut")["price"].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [ ]:
# Get the mean of the "price" column in the dataset grouped by the "color" column
diamonds.groupby("color")["price"].mean()

color
D    3169.954096
E    3076.752475
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

In [ ]:
# Get the maximum of the "price" column in the dataset grouped by the "color" column
diamonds.groupby("color")["price"].max()

color
D    18693
E    18731
F    18791
G    18818
H    18803
I    18823
J    18710
Name: price, dtype: int64

In [ ]:
# Get the column names of the dataset
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z', 'price_per_carat', 'is_expensive', 'rate'],
      dtype='str')

:

git hub:
* Git track changes in a repository (repo) - a project folder
* Every saved version is called a commit
* GitHub is cloud platform to store Git repositories online
* git push - uploads your local commits to GitHub (the remote repository)
* git pull - downloads new changes from GitHub to your local computer.

In [ ]:
# Git Setup Instructions for GitHub Repository

# 1. Create a new repository on the command line (if starting from scratch)
# echo "# Data-science-50058" >> README.md   # Create a README file with the repo name
# git init                                # Initialize a new local Git repository
# git add README.md                       # Stage the README file for commit
# git commit -m "first commit"            # Commit the staged file
# git branch -M main                      # Rename the default branch to 'main'
# git remote add origin https://github.com/hanitos/Data-science-50058.git # Link local repo to GitHub
# git push -u origin main                  # Push the local main branch to the remote origin

# 2. Push an existing repository from the command line
# git remote add origin https://github.com/hanitos/Data-science-50058.git # Link existing local repo to GitHub
# git branch -M main                      # Ensure the branch is named 'main'
# git push -u origin main                  # Push the local branch to the remote origin